1. Найти индексы ненулевых элементов в заданном массиве.

In [51]:
import numpy as np

# Create a sample array
arr = np.array([0, 1, 0, 2, 0, 3])

# Find indices of non-zero elements
nonzero_indices = np.nonzero(arr)
print(nonzero_indices)


(array([1, 3, 5], dtype=int64),)


2. Создать nxn единичную матрицу.

In [52]:
import numpy as np

n = 5
identity_matrix = np.eye(n)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


3. Создать массив nxnxn со случайными значениями

In [53]:
import numpy as np

n = 5
random_3d_array = np.random.rand(n, n, n)
print(random_3d_array)


[[[0.59662839 0.40521865 0.01762587 0.8082398  0.6336201 ]
  [0.53488516 0.1447378  0.34900244 0.33798007 0.38972253]
  [0.68158992 0.20834471 0.22251421 0.05719672 0.71860526]
  [0.68916274 0.12753055 0.51468742 0.97668178 0.63071199]
  [0.75899829 0.3094469  0.70941023 0.18571007 0.64572073]]

 [[0.24471596 0.10785131 0.50522127 0.82132481 0.81413597]
  [0.76862675 0.39370185 0.24031685 0.88365374 0.74222589]
  [0.54505026 0.88157988 0.72031771 0.26378776 0.24111168]
  [0.7022601  0.51155875 0.46990129 0.45023799 0.6742755 ]
  [0.20029199 0.39492883 0.74232632 0.93162999 0.77617946]]

 [[0.67357169 0.80069946 0.14584456 0.98136716 0.17590069]
  [0.52733644 0.18740073 0.55768738 0.93627958 0.91402775]
  [0.63903374 0.62512364 0.86533181 0.06709066 0.89733815]
  [0.36732702 0.53117056 0.57100604 0.11240344 0.56391247]
  [0.30408734 0.5578782  0.58756132 0.17468679 0.05384105]]

 [[0.46531626 0.37851738 0.70366329 0.58101858 0.35879387]
  [0.96979613 0.86529253 0.09084228 0.79842476 0.3

4. Создать вектор (одномерный массив) размера n, заполненный нулями

In [54]:
import numpy as np

n = 6
zero_vector = np.zeros(n)
print(zero_vector)

[0. 0. 0. 0. 0. 0.]


5. Создать вектор размера 1n, заполненный нулями, но пятый элемент равен 1

In [55]:
import numpy as np

n = 10
vector_with_one = np.zeros(n)
vector_with_one[4] = 1
print(vector_with_one)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


6. Создать вектор со значениями от n до m

In [57]:
import numpy as np

n = 1
m = 16
vector_range = np.arange(n, m)
print(vector_range)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


7. Развернуть одномерный массив (первый становится последним)

In [58]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)


[5 4 3 2 1]


8. Создать матрицу с 0 внутри, и 1 на границах

In [59]:
import numpy as np

n = 10
matrix = np.zeros((n, n))
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1
print(matrix)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


9. Создать nxn матрицу и заполнить её в шахматном порядке

In [60]:
import numpy as np

n = 4
matrix = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        matrix[i][j] = (i + j) % 2
print(matrix)


[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


10. Заменить максимальный элемент на ноль

In [61]:
import numpy as np

arr = np.array([1, 2, 3, 4, 99])
max_index = np.argmax(arr)
arr[max_index] = 0
print(arr)


[1 2 3 4 0]


11. Найти ближайшее к заданному значению число в заданном массиве

In [62]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
target = 3.1
closest = np.argmin(np.abs(arr - target))
print(arr[closest])


3


12. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [64]:
import numpy as np

array = np.random.rand(2, 2, 2, 2)
sum_last_two_axes = np.sum(array, axis=(2, 3))
print("array:\n", array,"\n")
print(sum_last_two_axes)


array:
 [[[[0.37987053 0.43639893]
   [0.30766554 0.19364447]]

  [[0.00656356 0.68369857]
   [0.99065916 0.35130412]]]


 [[[0.10915799 0.6217643 ]
   [0.46318169 0.89012436]]

  [[0.84702701 0.57759622]
   [0.91480498 0.88994656]]]] 

[[1.31757947 2.0322254 ]
 [2.08422834 3.22937477]]


13. Определить, есть ли в двумерном массиве нулевые столбцы

In [65]:
import numpy as np

array = np.array([[1, 0, 2], [3, 0, 5]])
has_zero_columns = np.any(array == 0, axis=0)
print(has_zero_columns)


[False  True False]


14. Отнять среднее из каждой строки в матрице

In [66]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]])
mean_subtracted = matrix - matrix.mean(axis=1)[:, np.newaxis]
print(mean_subtracted)
print("Mean:\n",matrix.mean(axis=1)[:, np.newaxis])


[[-0.5  0.5]
 [-0.5  0.5]]
Mean:
 [[1.5]
 [3.5]]


15. Создайте вектор с элементами от 10 до 50

In [67]:
import numpy as np

vector = np.arange(10, 51)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


16. Создайте матрицу (5, 5), заполненую от 0 до 6

In [68]:
import numpy as np


matrix = np.random.randint(0, 7, (5, 5))
print("Матрица 5x5:\n", matrix)


Матрица 5x5:
 [[0 6 4 4 1]
 [5 0 4 1 2]
 [5 4 5 1 5]
 [4 5 1 6 4]
 [5 5 4 4 1]]


17. Умножьте матрицу размерности (5, 3) на (3, 2)

In [69]:
import numpy as np

matrix_53 = np.random.rand(5, 3)
matrix_32 = np.random.rand(3, 2)
result = np.dot(matrix_53, matrix_32)
print("matrix 1:\n", matrix_53)
print("\n matrix 2:\n", matrix_32)
print("\n",result)


matrix 1:
 [[0.00884402 0.19355032 0.2128765 ]
 [0.36129102 0.44976644 0.30253652]
 [0.73888277 0.94327773 0.17862306]
 [0.57269502 0.23261174 0.84628569]
 [0.29526495 0.19761029 0.16186661]]

 matrix 2:
 [[0.39937502 0.98109742]
 [0.45006695 0.77597408]
 [0.96328054 0.09834617]]

 [[0.29570248 0.17980246]
 [0.63814316 0.7332221 ]
 [0.89169357 1.47444194]
 [1.14862148 0.82559924]
 [0.36278226 0.45894311]]


18. Создайте матрицу (10, 10) так, чтобы на границе были 0, а внтури 1

In [36]:
import numpy as np

n = 10
matrix = np.zeros((n, n))
matrix[1:-1, 1:-1] = 1
print(matrix)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


19. Для заданного числа найдите ближайший к нему элемент в векторе

In [70]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])
target = 3.1
closest_index = np.argmin(np.abs(vector - target))
print(vector[closest_index])


3


20. Дан трёхмерный массив "Цветное изображение", содержащий изображение, размера (height, width, numChannels), а также вектор коэффициентов длины numChannels. Сложить каналы изображения с указанными весами, и вернуть результат в виде матрицы размера (height, width). Реальное изображение не считываем, заполняем трехмерный массив случайными значениями. Преобразуйте цветное изображение в оттенки серого, использовав коэффициенты np.array([0.299, 0.587, 0.114]).

In [71]:
import numpy as np


height = 100
width = 100
num_channels = 3
random_image = np.random.rand(height, width, num_channels)

coefficients = np.array([0.299, 0.587, 0.114])


grayscale_image = np.dot(random_image, coefficients)

print(grayscale_image.shape)


(100, 100)
